/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import CheckoutSectionContainer from './checkout-section-container';
import CheckoutSectionContainerView from './checkout-section-container.view';

export * from './checkout-section-container';
export { ICheckoutSectionContainerConfig, ICheckoutSectionContainerProps, width } from './checkout-section-container.props.autogenerated';
export * from './checkout-section-container.view';
export * from './components/loading';

export { CheckoutSectionContainer, CheckoutSectionContainerView };
