/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

/* eslint-disable no-duplicate-imports */
import CheckoutShippingAddress from './checkout-shipping-address';
import CheckoutShippingAddressView from './checkout-shipping-address.view';

export * from './checkout-shipping-address';
export * from './checkout-shipping-address.data';
export {
    ICheckoutShippingAddressConfig,
    ICheckoutShippingAddressProps,
    ICheckoutShippingAddressResources
} from './checkout-shipping-address.props.autogenerated';
export * from './checkout-shipping-address.view';

export { CheckoutShippingAddress, CheckoutShippingAddressView };
